name: Remote Dispatch Action Initiator

on:
  repository_dispatch:

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        if: github.event.action != 'pong'
        run: |
          curl -X POST https://api.github.com/repos/marcnuri-demo/actions-remote-dispatch-b/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.t }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "PenguinMod-Gui" }}'
      - name: ACK - Acknowledge pong from remote repository
