name: Remote Dispatch Action Initiator
#test
on: [push]

permissions:
  contents: read

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ secrets.t }}
          event-type: update
          repository: PenguinMod/penguinmod.github.io
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: test
        run: npm run test
      - name: Repository Dispatch2
        uses: peter-evans/repository-dispatch@v2.0.1
        with:
          token: ${{ secrets.t }}
          event-type: update
          repository: PenguinMod/PenguinMod-Packager
